name: Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy backend app
        run: |
          kubectl apply -f backend.yaml


      - name: Deploy frontend app
        run: |
          kubectl apply -f frontend.yaml


      - name: Deploy secrets 
        run: |
          kubectl apply -f secret.yaml


      - name: Deploy configmap 
        run: |
          kubectl apply -f configmap.yaml

      - name: Deploy MySQL
        run: |
          kubectl apply -f mysql.yaml